#############################################################################
# Generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#  Nov 30, 2020 01:35:14 AM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1201x875+321+2
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "DBMS"
    vTcl:DefineAlias "$top" "dbms" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Artist 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "dbms" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Album 
    vTcl:DefineAlias "$top.lab46" "Label2" vTcl:WidgetProc "dbms" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Producer 
    vTcl:DefineAlias "$top.lab47" "Label3" vTcl:WidgetProc "dbms" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Year 
    vTcl:DefineAlias "$top.lab48" "Label4" vTcl:WidgetProc "dbms" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text ID 
    vTcl:DefineAlias "$top.lab49" "Label5" vTcl:WidgetProc "dbms" 1
    text $top.tex50 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 204 -wrap word 
    $top.tex50 configure -font "TkTextFont"
    $top.tex50 insert end text
    vTcl:DefineAlias "$top.tex50" "txtartist" vTcl:WidgetProc "dbms" 1
    text $top.tex51 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 204 -wrap word 
    $top.tex51 configure -font "TkTextFont"
    $top.tex51 insert end text
    vTcl:DefineAlias "$top.tex51" "txtalbum" vTcl:WidgetProc "dbms" 1
    text $top.tex52 \
        -background white -font TkTextFont -foreground black -height 33 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 204 -wrap word 
    $top.tex52 configure -font "TkTextFont"
    $top.tex52 insert end text
    vTcl:DefineAlias "$top.tex52" "txtpro" vTcl:WidgetProc "dbms" 1
    text $top.tex53 \
        -background white -font TkTextFont -foreground black -height 32 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 204 -wrap word 
    $top.tex53 configure -font "TkTextFont"
    $top.tex53 insert end text
    vTcl:DefineAlias "$top.tex53" "txtyear" vTcl:WidgetProc "dbms" 1
    text $top.tex54 \
        -background white -font TkTextFont -foreground black -height 33 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 204 -wrap word 
    $top.tex54 configure -font "TkTextFont"
    $top.tex54 insert end text
    vTcl:DefineAlias "$top.tex54" "txtid" vTcl:WidgetProc "dbms" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Song 
    vTcl:DefineAlias "$top.lab56" "Label6" vTcl:WidgetProc "dbms" 1
    text $top.tex57 \
        -background white -font TkTextFont -foreground black -height 36 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 204 -wrap word 
    $top.tex57 configure -font "TkTextFont"
    $top.tex57 insert end text
    vTcl:DefineAlias "$top.tex57" "Text1" vTcl:WidgetProc "dbms" 1
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Add 
    vTcl:DefineAlias "$top.but58" "btnadd" vTcl:WidgetProc "dbms" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Update 
    vTcl:DefineAlias "$top.but59" "btnupdate" vTcl:WidgetProc "dbms" 1
    button $top.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Delete 
    vTcl:DefineAlias "$top.but60" "btndelete" vTcl:WidgetProc "dbms" 1
    button $top.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Show 
    vTcl:DefineAlias "$top.but61" "btnshow" vTcl:WidgetProc "dbms" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family Impact -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Album Details} 
    vTcl:DefineAlias "$top.lab62" "Label7" vTcl:WidgetProc "dbms" 1
    label $top.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Album 
    vTcl:DefineAlias "$top.lab63" "Label8" vTcl:WidgetProc "dbms" 1
    text $top.tex64 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 214 -wrap word 
    $top.tex64 configure -font "TkTextFont"
    $top.tex64 insert end text
    vTcl:DefineAlias "$top.tex64" "txtalb1" vTcl:WidgetProc "dbms" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {No. of Tracks} 
    vTcl:DefineAlias "$top.lab65" "Label9" vTcl:WidgetProc "dbms" 1
    text $top.tex66 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 214 -wrap word 
    $top.tex66 configure -font "TkTextFont"
    $top.tex66 insert end text
    vTcl:DefineAlias "$top.tex66" "txtalb2" vTcl:WidgetProc "dbms" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family Impact -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Producer Details} 
    vTcl:DefineAlias "$top.lab67" "Label10" vTcl:WidgetProc "dbms" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Producer 
    vTcl:DefineAlias "$top.lab68" "Label11" vTcl:WidgetProc "dbms" 1
    label $top.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Contact 
    vTcl:DefineAlias "$top.lab69" "Label12" vTcl:WidgetProc "dbms" 1
    text $top.tex70 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 214 -wrap word 
    $top.tex70 configure -font "TkTextFont"
    $top.tex70 insert end text
    vTcl:DefineAlias "$top.tex70" "txtpro1" vTcl:WidgetProc "dbms" 1
    text $top.tex71 \
        -background white -font TkTextFont -foreground black -height 37 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 233 -wrap word 
    $top.tex71 configure -font "TkTextFont"
    $top.tex71 insert end text
    vTcl:DefineAlias "$top.tex71" "Text4" vTcl:WidgetProc "dbms" 1
    label $top.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family Impact -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Artist Details} 
    vTcl:DefineAlias "$top.lab73" "Label13" vTcl:WidgetProc "dbms" 1
    label $top.lab74 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Artist 
    vTcl:DefineAlias "$top.lab74" "Label14" vTcl:WidgetProc "dbms" 1
    label $top.lab75 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Contact 
    vTcl:DefineAlias "$top.lab75" "Label15" vTcl:WidgetProc "dbms" 1
    text $top.tex76 \
        -background white -font TkTextFont -foreground black -height 40 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 223 -wrap word 
    $top.tex76 configure -font "TkTextFont"
    $top.tex76 insert end text
    vTcl:DefineAlias "$top.tex76" "txtartist1" vTcl:WidgetProc "dbms" 1
    text $top.tex77 \
        -background white -font TkTextFont -foreground black -height 37 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 245 -wrap word 
    $top.tex77 configure -font "TkTextFont"
    $top.tex77 insert end text
    vTcl:DefineAlias "$top.tex77" "txtartist2" vTcl:WidgetProc "dbms" 1
    button $top.but80 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Album Details} 
    vTcl:DefineAlias "$top.but80" "btnalbum" vTcl:WidgetProc "dbms" 1
    button $top.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Producer Details} 
    vTcl:DefineAlias "$top.but81" "btnpro" vTcl:WidgetProc "dbms" 1
    button $top.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Artist Details} 
    vTcl:DefineAlias "$top.but82" "btnartist" vTcl:WidgetProc "dbms" 1
    label $top.lab50 \
        -background #f8f8f8 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$top.lab50" "lstmain" vTcl:WidgetProc "dbms" 1
    label $top.lab51 \
        -background #fbfbfb -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -text Label 
    vTcl:DefineAlias "$top.lab51" "lstsec" vTcl:WidgetProc "dbms" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.048 -y 0 -rely 0.051 -width 0 -relwidth 0.034 \
        -height 0 -relheight 0.03 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.114 -width 0 -relwidth 0.042 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.175 -width 0 -relwidth 0.05 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.048 -y 0 -rely 0.236 -width 0 -relwidth 0.034 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.048 -y 0 -rely 0.298 -width 0 -relwidth 0.034 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.tex50 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.051 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.tex51 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.113 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.tex52 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.175 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.tex53 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.236 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.033 -anchor nw -bordermode ignore 
    place $top.tex54 \
        -in $top -x 0 -relx 0.104 -y 0 -rely 0.298 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.736 -y 0 -rely 0.051 -width 0 -relwidth 0.034 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.tex57 \
        -in $top -x 0 -relx 0.784 -y 0 -rely 0.051 -width 0 -relwidth 0.163 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.38 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.12 -y 0 -rely 0.38 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 0 -relx 0.216 -y 0 -rely 0.38 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.312 -y 0 -rely 0.38 -width 56 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.04 -y 0 -rely 0.441 -width 0 -relwidth 0.178 \
        -height 0 -relheight 0.07 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.048 -y 0 -rely 0.513 -width 0 -relwidth 0.042 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.tex64 \
        -in $top -x 0 -relx 0.048 -y 0 -rely 0.544 -width 0 -relwidth 0.171 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.256 -y 0 -rely 0.513 -width 0 -relwidth 0.09 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.tex66 \
        -in $top -x 0 -relx 0.264 -y 0 -rely 0.544 -width 0 -relwidth 0.171 \
        -height 0 -relheight 0.035 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.031 -y 0 -rely 0.599 -width 0 -relwidth 0.218 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.668 -width 0 -relwidth 0.05 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.262 -y 0 -rely 0.668 -width 0 -relwidth 0.042 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.tex70 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.697 -width 0 -relwidth 0.171 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    place $top.tex71 \
        -in $top -x 0 -relx 0.262 -y 0 -rely 0.697 -width 0 -relwidth 0.179 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 0 -relx 0.038 -y 0 -rely 0.766 -width 0 -relwidth 0.171 \
        -height 0 -relheight 0.055 -anchor nw -bordermode ignore 
    place $top.lab74 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.835 -width 0 -relwidth 0.032 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    place $top.lab75 \
        -in $top -x 0 -relx 0.254 -y 0 -rely 0.835 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.026 -anchor nw -bordermode ignore 
    place $top.tex76 \
        -in $top -x 0 -relx 0.046 -y 0 -rely 0.864 -width 0 -relwidth 0.172 \
        -height 0 -relheight 0.039 -anchor nw -bordermode ignore 
    place $top.tex77 \
        -in $top -x 0 -relx 0.254 -y 0 -rely 0.864 -width 0 -relwidth 0.189 \
        -height 0 -relheight 0.036 -anchor nw -bordermode ignore 
    place $top.but80 \
        -in $top -x 0 -relx 0.57 -y 0 -rely 0.864 -width 106 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but81 \
        -in $top -x 0 -relx 0.731 -y 0 -rely 0.864 -width 116 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but82 \
        -in $top -x 0 -relx 0.893 -y 0 -rely 0.864 -width 106 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.316 -y 0 -rely 0.034 -width 0 -relwidth 0.36 \
        -height 0 -relheight 0.304 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.55 -y 0 -rely 0.423 -width 0 -relwidth 0.426 \
        -height 0 -relheight 0.373 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

